### ISSUE TITLE
Version for Apple Silicon (M1) ?

### ISSUE THREAD

**Issue by maxpiano** [dshnkao/SpaceId#11]
love this app, runs fine already in emulation mode on M1 mac. any chance of offering native ARM support in the future?

**Comment by dshnkao** [comment]
Hey @maxpiano 
I rebuild the app https://github.com/dshnkao/SpaceId/releases/tag/1.3.2. I don't have an M1 laptop to verify but let me know if it works for you.

**Comment by maxpiano** [comment]
wow, that was fast. app works perfectly! much thanks.
![image](https://user-images.githubusercontent.com/8249085/112055640-66520900-8b57-11eb-937d-f92d55324dcb.png)
