### ISSUE TITLE
Feature Request - Show active monitor

### ISSUE THREAD

**Issue by kunte0** [dshnkao/SpaceId#12]
Hi,

currently there is no way to tell which monitor is active.

![Screenshot](https://user-images.githubusercontent.com/33470032/112848061-f63c0980-90a7-11eb-9603-a1156e66e514.png)

It would be nice, especially when using yabai as a window manager, to see which monitor is currently active. Maybe like this, when 3 is active:

![Screenshot 2021-03-29 at 16 00 51](https://user-images.githubusercontent.com/33470032/112848505-6f3b6100-90a8-11eb-9768-7c5295e009a2.png)

Is it even possible? 

Ill check if i can make a Pull Request for this if i have more time on my hands.

**Comment by dshnkao** [comment]
It's a fairly easy change, wdyt of underlining?
<img width="158" alt="image" src="https://user-images.githubusercontent.com/4727299/114268908-027c7b00-9a47-11eb-972e-13bb4425725b.png">
<img width="154" alt="image" src="https://user-images.githubusercontent.com/4727299/114268911-13c58780-9a47-11eb-9658-9261c6384020.png">

**Comment by kunte0** [comment]
Looks great. Thanks for looking into it :)

**Comment by dshnkao** [comment]
https://github.com/dshnkao/SpaceId/releases/tag/v1.4

You can enable it here 😄 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/4727299/114269164-9864d580-9a48-11eb-89c6-42d2d92db559.png">
