### ISSUE TITLE
Homebrew Cask

### ISSUE THREAD

**Issue by binarious** [dshnkao/SpaceId#13]
Thank you for this great project. It would be nice to install and update it via [Homebrew Cask](https://github.com/Homebrew/homebrew-cask).

**Comment by jryom** [comment]
I have a cask I use personally, feel free to use/copy/modify to your liking: https://github.com/jryom/homebrew-formulae/blob/master/Casks/spaceid.rb

E.g.: 
```
```

**Comment by Aki-Riku** [comment]
There is now a cask available.

`
brew install --cask spaceid
`
