### ISSUE TITLE
App won't launch

### ISSUE THREAD

**Issue by georgesofianosgr** [dshnkao/SpaceId#7]
I couldn't launch latest release app.

I had to change the permissions of the 'SpaceId.app/Contents/MacOS/SpaceId' to be executable.

**Comment by dshnkao** [comment]
Would you happen to be using Catalina?

**Comment by georgesofianosgr** [comment]
Hey @dshnkao , yes I do.

**Comment by ilyam8** [comment]
Confirm, same problem on Catalina.

> The application “SpaceId” can’t be opened.

**Comment by ilyam8** [comment]
`WhiteSpace` works btw.

`SpaceId` was working after upgrade Mojave->Cataling. I did factory reset/reinstall and now it doesnt launch.

**Comment by dshnkao** [comment]
> `WhiteSpace` works btw.
> 
> `SpaceId` was working after upgrade Mojave->Catalina. I did factory reset/reinstall and now it doesnt launch.

Hi @ilyam8,
Thanks for reporting. Does @georgesofianosgr's work around work for you? Unfortunately, I don't have a Catalina machine with me to test this out atm.

**Comment by ilyam8** [comment]
Yes, it was 664, i changed to 764 and it fixed the problem. Somehow i missed change perms advice from the OP 😅
